// <auto-generated />
using System;
using ForumsService.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumsService.API.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20221206164537_Local")]
    partial class Local
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ForumsService.Domain.Entities.ForumDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Forums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e0b0cee-0e4a-498c-a429-faece79c5722"),
                            Description = "A Forum for the Dune movie.",
                            Name = "dune_forum"
                        },
                        new
                        {
                            Id = new Guid("6d61e13a-ccc5-4f00-add9-a31b9a8f3ad1"),
                            Description = "A Forum for the Star Wars movies.",
                            Name = "sw_forum"
                        },
                        new
                        {
                            Id = new Guid("90d307e6-7710-4f51-8d00-f13bd6eae519"),
                            Description = "A Forum for the Harry Potter movies.",
                            Name = "hp_forum"
                        });
                });

            modelBuilder.Entity("ForumsService.Domain.Entities.ThreadDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ForumId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ForumId");

                    b.ToTable("Threads");
                });

            modelBuilder.Entity("ForumsService.Domain.Entities.ThreadDto", b =>
                {
                    b.HasOne("ForumsService.Domain.Entities.ForumDto", "Forum")
                        .WithMany("Threads")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forum");
                });

            modelBuilder.Entity("ForumsService.Domain.Entities.ForumDto", b =>
                {
                    b.Navigation("Threads");
                });
#pragma warning restore 612, 618
        }
    }
}
