// <auto-generated />
using System;
using ForumsService.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumsService.API.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    [Migration("20221104122609_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ForumsService.Domain.Entities.ForumDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Forums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33759f86-a587-4937-b164-cbc81861a6c6"),
                            Description = "A Forum for the Dune movie.",
                            Name = "dune_forum"
                        },
                        new
                        {
                            Id = new Guid("f2562859-79d9-46b5-87ce-5998d19339ef"),
                            Description = "A Forum for the Star Wars movies.",
                            Name = "sw_forum"
                        },
                        new
                        {
                            Id = new Guid("5922bfaa-680f-4b72-a290-8c1e160849de"),
                            Description = "A Forum for the Harry Potter movies.",
                            Name = "hp_forum"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
