// <auto-generated />
using System;
using ForumsService.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumsService.API.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    partial class ForumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ForumsService.Domain.Entities.ForumDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Forums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("322a0aef-0e55-4bb9-b7a2-90f582fd9f35"),
                            Description = "A Forum for the Dune movie.",
                            Name = "dune_forum"
                        },
                        new
                        {
                            Id = new Guid("f2e9d7e3-a591-4e51-ad20-eb4b4d492b68"),
                            Description = "A Forum for the Star Wars movies.",
                            Name = "sw_forum"
                        },
                        new
                        {
                            Id = new Guid("7f1871b3-9a57-4c99-af8d-50b55e8f48e7"),
                            Description = "A Forum for the Harry Potter movies.",
                            Name = "hp_forum"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
