// <auto-generated />
using System;
using ForumsService.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumsService.API.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    partial class ForumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ForumsService.Domain.Entities.ForumDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Forums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c86946bf-0fc3-4d96-8749-c50b91334538"),
                            Description = "A Forum for the Dune movie.",
                            Name = "dune_forum"
                        },
                        new
                        {
                            Id = new Guid("14ec41f0-9325-4457-9eb2-56ec72fd3e0b"),
                            Description = "A Forum for the Star Wars movies.",
                            Name = "sw_forum"
                        },
                        new
                        {
                            Id = new Guid("4c6bb740-f042-4e41-a7bd-d21a1be5ee07"),
                            Description = "A Forum for the Harry Potter movies.",
                            Name = "hp_forum"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
