// <auto-generated />
using System;
using ForumsService.Infrastructure.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ForumsService.API.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    partial class ForumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ForumsService.Domain.Entities.ForumDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Forums", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66f9fcc0-ad97-4422-bddd-7c208eef5be5"),
                            Description = "A Forum for the Dune movie.",
                            Name = "dune_forum"
                        },
                        new
                        {
                            Id = new Guid("b1b263b4-c588-4add-89c2-eded5632d0a1"),
                            Description = "A Forum for the Star Wars movies.",
                            Name = "sw_forum"
                        },
                        new
                        {
                            Id = new Guid("89816887-fdff-4c0f-90d0-05178002fe46"),
                            Description = "A Forum for the Harry Potter movies.",
                            Name = "hp_forum"
                        });
                });

            modelBuilder.Entity("ForumsService.Domain.Entities.ThreadDto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ForumId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ForumId");

                    b.ToTable("Threads");
                });

            modelBuilder.Entity("ForumsService.Domain.Entities.ThreadDto", b =>
                {
                    b.HasOne("ForumsService.Domain.Entities.ForumDto", "Forum")
                        .WithMany("Threads")
                        .HasForeignKey("ForumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Forum");
                });

            modelBuilder.Entity("ForumsService.Domain.Entities.ForumDto", b =>
                {
                    b.Navigation("Threads");
                });
#pragma warning restore 612, 618
        }
    }
}
